# SPDX-FileCopyrightText: 2022 James R. Barlow
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
        exclude: \.rst$
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.3
    hooks:
      - id: clang-format
        files: "src/.*\\.(cpp|h|hpp)?$"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.5"
    hooks:
      - id: ruff
        files: "src/.*\\.pyi?$"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        exclude: "tests/.*\\.py$"
        additional_dependencies:
          - lxml-stubs
          - types-Deprecated
          - types-Pillow
          - types-requests
          - types-setuptools
